-- MySQL Script generated by MySQL Workbench
-- Wed Jan 27 16:17:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vezetvsem
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vezetvsem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vezetvsem` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vezetvsem` ;

-- -----------------------------------------------------
-- Table `vezetvsem`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vezetvsem`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(145) NOT NULL COMMENT 'имя',
  `lastname` VARCHAR(145) NOT NULL COMMENT 'фамилия ',
  `email` VARCHAR(245) NOT NULL COMMENT 'эл почта',
  `phone` BIGINT(12) NOT NULL COMMENT 'телефон',
  `password_hash` CHAR(65) NULL DEFAULT NULL COMMENT 'пароль',
  `location_index` INT NOT NULL,
  `status_user` ENUM('customer', 'contractor') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vezetvsem`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vezetvsem`.`customers` (
  `users_id` INT UNSIGNED NOT NULL,
  `bithday` DATE NOT NULL,
  `adress` VARCHAR(245) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  INDEX `fk_profiles_users_idx` (`users_id` ASC) VISIBLE,
  PRIMARY KEY (`users_id`),
  CONSTRAINT `fk_profiles_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `vezetvsem`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vezetvsem`.`favorite_users_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vezetvsem`.`favorite_users_request` (
  `from_users_id` INT UNSIGNED NOT NULL,
  `to_users_id` INT UNSIGNED NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '-1 отклонен\n0 запрос\n1 принят',
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NULL,
  INDEX `fk_favorite_users_request_users1_idx` (`from_users_id` ASC) VISIBLE,
  INDEX `fk_favorite_users_request_users2_idx` (`to_users_id` ASC) VISIBLE,
  PRIMARY KEY (`from_users_id`, `to_users_id`),
  CONSTRAINT `fk_favorite_users_request_users1`
    FOREIGN KEY (`from_users_id`)
    REFERENCES `vezetvsem`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorite_users_request_users2`
    FOREIGN KEY (`to_users_id`)
    REFERENCES `vezetvsem`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vezetvsem`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vezetvsem`.`messages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `from_users_id` INT UNSIGNED NOT NULL,
  `to_users_id` INT UNSIGNED NOT NULL,
  `text` VARCHAR(545) NULL DEFAULT NULL,
  `media_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `from_users_idx` (`from_users_id` ASC) INVISIBLE,
  INDEX `fk_messages_users1_idx` (`to_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_messages_users`
    FOREIGN KEY (`from_users_id`)
    REFERENCES `vezetvsem`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`to_users_id`)
    REFERENCES `vezetvsem`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vezetvsem`.`application_for_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vezetvsem`.`application_for_order` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(145) NOT NULL COMMENT 'название заявки',
  `description` VARCHAR(545) NOT NULL COMMENT 'подробное описание заявки услуги (вес, габариты, желаемая дата и время, адрес доставки: откуда и куда)',
  `comments` VARCHAR(545) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vezetvsem`.`users_communication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vezetvsem`.`users_communication` (
  `application_for_order_id` INT UNSIGNED NOT NULL,
  `users_id` INT UNSIGNED NOT NULL,
  INDEX `fk_users_communication_application_for_order1_idx` (`application_for_order_id` ASC) VISIBLE,
  INDEX `fk_users_communication_users1_idx` (`users_id` ASC) VISIBLE,
  PRIMARY KEY (`application_for_order_id`, `users_id`),
  CONSTRAINT `fk_users_communication_application_for_order1`
    FOREIGN KEY (`application_for_order_id`)
    REFERENCES `vezetvsem`.`application_for_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_communication_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `vezetvsem`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vezetvsem`.`media_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vezetvsem`.`media_types` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vezetvsem`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vezetvsem`.`media` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_id` INT UNSIGNED NOT NULL,
  `media_types_id` INT UNSIGNED NOT NULL,
  `url` VARCHAR(45) NULL DEFAULT NULL,
  `blob` BLOB NULL DEFAULT NULL,
  `size` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_media_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_media_media_types1_idx` (`media_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_media_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `vezetvsem`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_media_types1`
    FOREIGN KEY (`media_types_id`)
    REFERENCES `vezetvsem`.`media_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vezetvsem`.`service_providers_urlico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vezetvsem`.`service_providers_urlico` (
  `users_id` INT UNSIGNED NOT NULL,
  `name_of_organisation` VARCHAR(145) NOT NULL,
  `OGRN` VARCHAR(100) NOT NULL,
  `INN` VARCHAR(100) NOT NULL,
  `KPP` VARCHAR(100) NOT NULL,
  `bank_details` VARCHAR(100) NOT NULL,
  `raschetniy_schet` VARCHAR(55) NOT NULL,
  `korrespond_schet` VARCHAR(55) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `cars_number` INT NOT NULL DEFAULT 0 COMMENT 'кол-во авто в парке',
  `cars_types_id` INT UNSIGNED NOT NULL COMMENT 'вид авто',
  PRIMARY KEY (`users_id`),
  UNIQUE INDEX `KPP_UNIQUE` (`KPP` ASC) VISIBLE,
  UNIQUE INDEX `INN_UNIQUE` (`INN` ASC) VISIBLE,
  UNIQUE INDEX `raschetniy_schet_UNIQUE` (`raschetniy_schet` ASC) VISIBLE,
  UNIQUE INDEX `korrespond_schet_UNIQUE` (`korrespond_schet` ASC) VISIBLE,
  INDEX `fk_service_providers_urlico_users1_idx` (`users_id` ASC) VISIBLE,
  UNIQUE INDEX `OGRN_UNIQUE` (`OGRN` ASC) VISIBLE,
  CONSTRAINT `fk_service_providers_urlico_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `vezetvsem`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vezetvsem`.`service_providers_ind_predpr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vezetvsem`.`service_providers_ind_predpr` (
  `users_id` INT UNSIGNED NOT NULL,
  `mesto_registracii` VARCHAR(245) NOT NULL,
  `OGRN` VARCHAR(245) NOT NULL,
  `bank_details` VARCHAR(245) NOT NULL,
  `raschetniy_schet` VARCHAR(55) NOT NULL,
  `korrespond_schet` VARCHAR(55) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `cars_number` INT NOT NULL DEFAULT 0,
  `cars_types_id` INT UNSIGNED NOT NULL,
  INDEX `fk_service_providers_ind_predpr_users1_idx` (`users_id` ASC) VISIBLE,
  PRIMARY KEY (`users_id`),
  UNIQUE INDEX `OGRN_UNIQUE` (`OGRN` ASC) VISIBLE,
  UNIQUE INDEX `raschetniy_schet_UNIQUE` (`raschetniy_schet` ASC) VISIBLE,
  UNIQUE INDEX `korrespond_schet_UNIQUE` (`korrespond_schet` ASC) VISIBLE,
  CONSTRAINT `fk_service_providers_ind_predpr_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `vezetvsem`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vezetvsem`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vezetvsem`.`orders` (
  `application_for_order_id` INT UNSIGNED NOT NULL,
  `number` VARCHAR(45) NOT NULL COMMENT 'номер договора ',
  `price` FLOAT NOT NULL DEFAULT 0 COMMENT 'стоимость',
  `date_of_registration` DATETIME NOT NULL DEFAULT NOW(),
  `date_of_end` DATETIME NOT NULL,
  `status` ENUM('completed', 'not_completed') NOT NULL,
  INDEX `fk_order_application_for_order1_idx` (`application_for_order_id` ASC) VISIBLE,
  PRIMARY KEY (`application_for_order_id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  CONSTRAINT `fk_order_application_for_order1`
    FOREIGN KEY (`application_for_order_id`)
    REFERENCES `vezetvsem`.`application_for_order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vezetvsem`.`users_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vezetvsem`.`users_settings` (
  `users_id` INT UNSIGNED NOT NULL,
  `notification_messages` ENUM('on', 'off') NOT NULL,
  `notification_followers` ENUM('on', 'off') NOT NULL,
  `notification_comments` ENUM('on', 'off') NOT NULL,
  INDEX `fk_users_settings_users1_idx` (`users_id` ASC) VISIBLE,
  PRIMARY KEY (`users_id`),
  CONSTRAINT `fk_users_settings_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `vezetvsem`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vezetvsem`.`cars_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vezetvsem`.`cars_types` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL COMMENT 'марка авто',
  `load_capacity` INT NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `service_providers_ind_predpr_users_id` INT UNSIGNED NOT NULL,
  `service_providers_urlico_users_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cars_types_service_providers_ind_predpr1_idx` (`service_providers_ind_predpr_users_id` ASC) VISIBLE,
  INDEX `fk_cars_types_service_providers_urlico1_idx` (`service_providers_urlico_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_cars_types_service_providers_ind_predpr1`
    FOREIGN KEY (`service_providers_ind_predpr_users_id`)
    REFERENCES `vezetvsem`.`service_providers_ind_predpr` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cars_types_service_providers_urlico1`
    FOREIGN KEY (`service_providers_urlico_users_id`)
    REFERENCES `vezetvsem`.`service_providers_urlico` (`users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
